### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by birkenfeld** [andrew-d/interfaces-rs#16]
Compilation on i686 systems is broken with 0.0.3. Commit 1fb5ffe98192b72b35c02139bad670aabec59517 seems to fix it, but is unreleased.

Thanks!

**Comment by andrew-d** [comment]
Done!  Just pushed version [0.0.4][1].

[1]: https://github.com/andrew-d/interfaces-rs/releases/tag/v0.0.4
