### ISSUE TITLE
How to get the gateway IP address

### ISSUE THREAD

**Issue by nocker01** [andrew-d/interfaces-rs#26]
Hi,
I've tried to figure this out but have not had any luck in finding the answer.  Is there a way to obtain the gateway IP address for an interface?
Thanks.

**Comment by dalance** [comment]
In my understanding, gateway IP address is not associated with interface.
It is managed by routing table.
https://crates.io/crates/rtnetlink may be helpful.

**Comment by nocker01** [comment]
Thank you, I will look there.
